### ISSUE TITLE
On Android mobile chrome if 'setInterval' is used web2app doesn't work

### ISSUE THREAD

**Issue by rockmkd** [html5crew/web2app#11]
Android 의 Chrome 에서만 발생하는 것 같습니다.
web2app.js 가 include 된 페이지에서 setInterval 함수가 사용되면(interval < 2000) app으로 이동하지 않네요.
interval이 길면 잘 이동합니다.

**Comment by dduskim** [comment]
넵 확인했습니다.
intent 의 경우 로깅을 위해 100ms 딜레이를 주도록 setTimeout 으로 한번 덮고 있는 것 외에 특별한 타이밍 이슈가 발생할만한 부분이 없는데요. 최신버전의 크롬에서는 문제가 있네요.
function web2appViaIntentURI (launchURI) {
    setTimeout(function () {
        top.location.href = launchURI;
    }, 100);
}
https://gist.github.com/dduskim/d7c2e704adb134f62cc1

특정 타이밍(interval < 2000)이나 정확한 원인은 파악하지 못했습니다.
해당 이슈는 확인되면 공유드리도록 할게요
